
const testURL = 'https://gist.githubusercontent.com/simonsarris/9980a385af4f4c4d3967/raw/e4ba954591aaa5de8e4d36a4952e6229402e0fbd/poem.txt'


export const getTextInputAlphabetical = {url: testURL, filter: "Alphabetical"}

export const getTextOutputAlphabetical = [
  {word: 'a', count: 2}, 
  {word: 'agony', count: 1}, 
  {word: 'alone', count: 1}, 
  {word: 'and', count: 4}, 
  {word: 'any', count: 1},  
  {word: 'as', count: 1}, 
  {word: 'at', count: 2},  
  {word: 'be', count: 1}, 
  {word: 'beating', count: 1}, 
  {word: 'before', count: 1}, 
  {word: 'bird', count: 1}, 
  {word: 'by', count: 1}, 
  {word: 'can', count: 1}, 
  {word: 'crown', count: 1}, 
  {word: 'day', count: 1}, 
  {word: 'declines', count: 1}, 
  {word: 'die', count: 4}, 
  {word: 'dream', count: 1}, 
  {word: 'expires', count: 1}, 
  {word: 'facing', count: 1}, 
  {word: 'fades', count: 1}, 
  {word: 'fleeting', count: 1}, 
  {word: 'fly', count: 1}, 
  {word: 'from', count: 1}, 
  {word: 'gentle', count: 1}, 
  {word: 'golden', count: 1}, 
  {word: 'green', count: 1}, 
  {word: 'guti', count: 1}, 
  {word: 'hear', count: 1}, 
  {word: 'hearts', count: 1}, 
  {word: 'high', count: 1}, 
  {word: 'i', count: 1}, 
  {word: "i'm", count: 1}, 
  {word: 'its', count: 1}, 
  {word: 'jera', count: 1}, 
  {word: 'know', count: 1}, 
  {word: 'last', count: 1}, 
  {word: 'lies', count: 1}, 
  {word: 'life', count: 1}, 
  {word: 'light', count: 1}, 
  {word: 'like', count: 3}, 
  {word: 'luminous', count: 1}, 
  {word: 'majestic', count: 1}, 
  {word: 'manuel', count: 1}, 
  {word: 'moment', count: 1}, 
  {word: 'more', count: 1}, 
  {word: 'my', count: 1}, 
  {word: 'n', count: 1}, 
  {word: 'network', count: 1}, 
  {word: 'nor', count: 1}, 
  {word: 'not', count: 1}, 
  {word: 'of', count: 1}, 
  {word: 'once', count: 1}, 
  {word: 'our', count: 1}, 
  {word: 'prayers', count: 1}, 
  {word: 'removes', count: 1}, 
  {word: 'retires', count: 1}, 
  {word: 'rrez', count: 1}, 
  {word: 'sad', count: 1}, 
  {word: 'says', count: 1}, 
  {word: 'sea', count: 2}, 
  {word: 'seems', count: 1}, 
  {word: 'she', count: 1}, 
  {word: 'sky', count: 2}, 
  {word: 'slowly', count: 1}, 
  {word: 'something', count: 1}, 
  {word: 'soul', count: 1}, 
  {word: 'still', count: 1}, 
  {word: 'sun', count: 1}, 
  {word: 'than', count: 1}, 
  {word: 'that', count: 4}, 
  {word: 'the', count: 8}, 
  {word: 'this', count: 1}, 
  {word: 'though', count: 1}, 
  {word: 'time', count: 1}, 
  {word: 'to', count: 5}, 
  {word: 'very', count: 1}, 
  {word: 'voices', count: 1}, 
  {word: 'want', count: 1}, 
  {word: 'waves', count: 2}, 
  {word: 'we', count: 1}, 
  {word: 'weeping', count: 1}, 
  {word: 'when', count: 1}, 
  {word: 'while', count: 2}, 
  {word: 'with', count: 2}, 
  {word: 'young', count: 1}, 
  {word: 'yours', count: 1}]

export const getTextInputDescending = {url: testURL, filter: "Descending"}

export const getTextOutputDescending = [ 
{word: 'by', count: 1}, 
{word: 'manuel', count: 1}, 
{word: 'guti', count: 1}, 
{word: 'rrez', count: 1}, 
{word: 'n', count: 1}, 
{word: 'jera', count: 1}, 
{word: 'i', count: 1}, 
{word: 'want', count: 1}, 
{word: 'as', count: 1}, 
{word: 'day', count: 1}, 
{word: 'declines', count: 1}, 
{word: 'high', count: 1}, 
{word: 'facing', count: 1}, 
{word: 'agony', count: 1}, 
{word: 'seems', count: 1}, 
{word: 'dream', count: 1}, 
{word: 'my', count: 1}, 
{word: 'soul', count: 1}, 
{word: 'bird', count: 1}, 
{word: 'can', count: 1}, 
{word: 'fly', count: 1}, 
{word: 'hear', count: 1}, 
{word: 'not', count: 1}, 
{word: 'this', count: 1}, 
{word: 'last', count: 1}, 
{word: 'moment', count: 1}, 
{word: 'once', count: 1}, 
{word: 'alone', count: 1}, 
{word: 'any', count: 1}, 
{word: 'more', count: 1}, 
{word: 'voices', count: 1}, 
{word: 'nor', count: 1}, 
{word: 'weeping', count: 1}, 
{word: 'prayers', count: 1}, 
{word: 'than', count: 1}, 
{word: 'majestic', count: 1}, 
{word: 'beating', count: 1}, 
{word: 'of', count: 1}, 
{word: 'when', count: 1}, 
{word: 'sad', count: 1}, 
{word: 'light', count: 1}, 
{word: 'retires', count: 1}, 
{word: 'its', count: 1}, 
{word: 'golden', count: 1}, 
{word: 'network', count: 1}, 
{word: 'from', count: 1}, 
{word: 'green', count: 1}, 
{word: 'be', count: 1}, 
{word: 'sun', count: 1}, 
{word: 'slowly', count: 1}, 
{word: 'expires', count: 1}, 
{word: 'something', count: 1}, 
{word: 'very', count: 1}, 
{word: 'luminous', count: 1}, 
{word: 'fades', count: 1}, 
{word: 'young', count: 1}, 
{word: 'before', count: 1}, 
{word: 'fleeting', count: 1}, 
{word: 'time', count: 1}, 
{word: 'removes', count: 1}, 
{word: 'gentle', count: 1}, 
{word: 'crown', count: 1}, 
{word: 'life', count: 1}, 
{word: 'still', count: 1}, 
{word: 'says', count: 1}, 
{word: "i'm", count: 1}, 
{word: 'yours', count: 1}, 
{word: 'though', count: 1}, 
{word: 'we', count: 1}, 
{word: 'know', count: 1}, 
{word: 'our', count: 1}, 
{word: 'hearts', count: 1}, 
{word: 'she', count: 1}, 
{word: 'lies', count: 1}, 
{word: 'at', count: 2}, 
{word: 'sea', count: 2}, 
{word: 'sky', count: 2}, 
{word: 'while', count: 2}, 
{word: 'a', count: 2}, 
{word: 'with', count: 2}, 
{word: 'waves', count: 2}, 
{word: 'like', count: 3}, 
{word: 'die', count: 4}, 
{word: 'and', count: 4}, 
{word: 'that', count: 4}, 
{word: 'to', count: 5}, 
{word: 'the', count: 8}



]

export const getTextInputAscending = {url: testURL, filter: 'Ascending'}

export const getTextOutputAscending = [
  {word: 'the', count: 8}, 
  {word: 'to', count: 5}, 
  {word: 'die', count: 4}, 
  {word: 'and', count: 4}, 
  {word: 'that', count: 4}, 
  {word: 'like', count: 3}, 
  {word: 'at', count: 2}, 
  {word: 'sea', count: 2}, 
  {word: 'sky', count: 2}, 
  {word: 'while', count: 2}, 
  {word: 'a', count: 2}, 
  {word: 'with', count: 2}, 
  {word: 'waves', count: 2}, 
  {word: 'by', count: 1}, 
  {word: 'manuel', count: 1}, 
  {word: 'guti', count: 1}, 
  {word: 'rrez', count: 1}, 
  {word: 'n', count: 1}, 
  {word: 'jera', count: 1}, 
  {word: 'i', count: 1}, 
  {word: 'want', count: 1}, 
  {word: 'as', count: 1}, 
  {word: 'day', count: 1}, 
  {word: 'declines', count: 1}, 
  {word: 'high', count: 1}, 
  {word: 'facing', count: 1}, 
  {word: 'agony', count: 1}, 
  {word: 'seems', count: 1}, 
  {word: 'dream', count: 1}, 
  {word: 'my', count: 1}, 
  {word: 'soul', count: 1}, 
  {word: 'bird', count: 1}, 
  {word: 'can', count: 1},  
  {word: 'fly', count: 1}, 
  {word: 'hear', count: 1}, 
  {word: 'not', count: 1}, 
  {word: 'this', count: 1}, 
  {word: 'last', count: 1}, 
  {word: 'moment', count: 1}, 
  {word: 'once', count: 1}, 
  {word: 'alone', count: 1}, 
  {word: 'any', count: 1}, 
  {word: 'more', count: 1}, 
  {word: 'voices', count: 1}, 
  {word: 'nor', count: 1}, 
  {word: 'weeping', count: 1}, 
  {word: 'prayers', count: 1}, 
  {word: 'than', count: 1}, 
  {word: 'majestic', count: 1}, 
  {word: 'beating', count: 1}, 
  {word: 'of', count: 1}, 
  {word: 'when', count: 1}, 
  {word: 'sad', count: 1}, 
  {word: 'light', count: 1}, 
  {word: 'retires', count: 1}, 
  {word: 'its', count: 1}, 
  {word: 'golden', count: 1}, 
  {word: 'network', count: 1}, 
  {word: 'from', count: 1}, 
  {word: 'green', count: 1}, 
  {word: 'be', count: 1}, 
  {word: 'sun', count: 1}, 
  {word: 'slowly', count: 1}, 
  {word: 'expires', count: 1}, 
  {word: 'something', count: 1}, 
  {word: 'very', count: 1}, 
  {word: 'luminous', count: 1}, 
  {word: 'fades', count: 1}, 
  {word: 'young', count: 1}, 
  {word: 'before', count: 1}, 
  {word: 'fleeting', count: 1}, 
  {word: 'time', count: 1}, 
  {word: 'removes', count: 1}, 
  {word: 'gentle', count: 1}, 
  {word: 'crown', count: 1}, 
  {word: 'life', count: 1}, 
  {word: 'still', count: 1}, 
  {word: 'says', count: 1}, 
  {word: "i'm", count: 1}, 
  {word: 'yours', count: 1}, 
  {word: 'though', count: 1}, 
  {word: 'we', count: 1}, 
  {word: 'know', count: 1}, 
  {word: 'our', count: 1}, 
  {word: 'hearts', count: 1}, 
  {word: 'she', count: 1}, 
  {word: 'lies', count: 1}]

export const getTextInput = {url: testURL, filter: null}

export const getTextOutput = [
  {word: 'by', count: 1},
  {word: 'manuel', count: 1} , 
  {word: 'guti', count: 1} , 
  {word: 'rrez', count: 1} , 
  {word: 'n', count: 1} , 
  {word: 'jera', count: 1} , 
  {word: 'i', count: 1} , 
  {word: 'want', count: 1} , 
  {word: 'to', count: 5},  
  {word: 'die', count: 4} , 
  {word: 'as', count: 1}  , {word: 'the', count: 8}  , {word: 'day', count: 1}  , 
  {word: 'declines', count: 1}  , {word: 'at', count: 2}  , {word: 'high', count: 1}  , 
  {word: 'sea', count: 2}  , {word: 'and', count: 4}  , {word: 'facing', count: 1}  , 
  {word: 'sky', count: 2}  , {word: 'while', count: 2}  , {word: 'agony', count: 1}  , 
  {word: 'seems', count: 1}  , {word: 'like', count: 3}  , {word: 'a', count: 2}  , 
  {word: 'dream', count: 1}  , {word: 'my', count: 1}  , {word: 'soul', count: 1}  , 
  {word: 'bird', count: 1}  , {word: 'that', count: 4}  , {word: 'can', count: 1}  , 
  {word: 'fly', count: 1}  , {word: 'hear', count: 1}  , {word: 'not', count: 1}  , 
  {word: 'this', count: 1}  , {word: 'last', count: 1}  , {word: 'moment', count: 1}  , 
  {word: 'once', count: 1}  , {word: 'alone', count: 1}  , {word: 'with', count: 2}  , 
  {word: 'any', count: 1}  , {word: 'more', count: 1}  , {word: 'voices', count: 1}  , 
  {word: 'nor', count: 1}  , {word: 'weeping', count: 1}  , {word: 'prayers', count: 1}  , 
  {word: 'than', count: 1}  , {word: 'majestic', count: 1}  , {word: 'beating', count: 1}  , 
  {word: 'of', count: 1}  , {word: 'waves', count: 2}  , {word: 'when', count: 1}  , 
  {word: 'sad', count: 1}  , {word: 'light', count: 1}  , {word: 'retires', count: 1}  , 
  {word: 'its', count: 1}  , {word: 'golden', count: 1}  , {word: 'network', count: 1}  , 
  {word: 'from', count: 1}  , {word: 'green', count: 1}  , {word: 'be', count: 1}  , 
  {word: 'sun', count: 1}  , {word: 'slowly', count: 1}  , {word: 'expires', count: 1}  , 
  {word: 'something', count: 1}  , {word: 'very', count: 1}  , {word: 'luminous', count: 1}  , 
  {word: 'fades', count: 1}  , {word: 'young', count: 1}  , {word: 'before', count: 1}  , 
  {word: 'fleeting', count: 1}  , {word: 'time', count: 1}  , {word: 'removes', count: 1}  , 
  {word: 'gentle', count: 1}  , {word: 'crown', count: 1}  , {word: 'life', count: 1}  , 
  {word: 'still', count: 1}  , {word: 'says', count: 1}  , {word: "i'm", count: 1}  , 
  {word: 'yours', count: 1}  , {word: 'though', count: 1}  , {word: 'we', count: 1}  , 
  {word: 'know', count: 1}  , {word: 'our', count: 1}  , {word: 'hearts', count: 1}  , 
  {word: 'she', count: 1}  , {word: 'lies', count: 1}]
